name: ci
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: grokloc/grokloc-go:dev
      env:
        GROKLOC_ENV: "UNIT"
        APP_HOST: "localhost"
        APP_PORT: "3000"
        CI: "1"
    steps:
      - uses: actions/checkout@v2
      - run: golangci-lint --timeout=24h run pkg/...
      - run: golint pkg/...
      - run: go test -v -race ./...
